### PR TITLE
School page removed; Other minute changes

### PR DESCRIPTION
**Pull request by Priyansdesai**
Hi Michael, 

If you can merge this, it would be great. 

Thanks,
Priyans

### CODE REVIEW

**Comment by cycomachead** [comment]
Hey can you merge in the master branch? (Click on the command line instructions link for info on resolving the conflicts.)

Thanks!

**Comment by Priyansdesai** [comment]
Hey, I did make a pull request from my master branch to the beautyjoy.github.io's master branch. In terms of resolving the conflicts do you want me to pull the most recent code

**Comment by cycomachead** [comment]
Yeah, the most recent code, in beautyjoy/master. 

Thanks!

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by Priyansdesai** [comment]
Hey,

I fixed the conflicts, but another problem has occurred. The link /india/ doesn't redirect to /india-pd/, even though I have put:
redirect_form:
- /summer-pd/india/
- /india/

Is there a way, you can help me on this? I am sorry I am troubling you a lot

**Pull request merged**
